### PR TITLE
changes made

### PR DESCRIPTION
**Pull request by PieterCoppens-IS**
I added the birth date of the author.

### CODE REVIEW

**Comment by OpenITI-Training** [comment]
Hi Pieter, good to see this worked out. Gowaart told me you had some difficulties creating the pull request. Is it clear now?

**Comment by PieterCoppens-IS** [comment]
I'm not really sure what did the trick in the end, but suddenly everything
fell in its place. I think I have to do it again with a different file over
the next couple of days to see if I can do the trick again.

**Comment by OpenITI-Training** [comment]
Yes, this is the type of thing you only learn (and remember) by repeating it often. We'll try to include forking, cloning, pushing, etc. in the exercises for the next sessions as well. I have updated the slides on creating the pull requests after Gowaart told me you ran into trouble there (with a more direct way to create the pull request), could you take a look and see if it is clearer now? It's slides numbers 57-58.

**Comment by PieterCoppens-IS** [comment]
It's clear! But it was initially clear already (I rewatched the
recordings), I think there was something wrong in my github-update.

**Comment by PieterCoppens-IS** [comment]
I will give it another try with the *real* file outside the practice area
now, I will add the birth date to the file.

**Pull request merged**
